# Generated by Django 5.1.3 on 2026-02-03 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emplooye",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=150, verbose_name="Nombres")),
                (
                    "dni",
                    models.CharField(max_length=10, unique=True, verbose_name="dni"),
                ),
                (
                    "date_joined",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Fecha de registro"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("date_update", models.DateTimeField(auto_now_add=True)),
                ("age", models.PositiveIntegerField(default=0)),
                (
                    "salaria",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                ("state", models.BooleanField(default=True)),
                ("gender", models.CharField(max_length=50)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatar/%Y/%m/%d"
                    ),
                ),
                (
                    "cvtae",
                    models.FileField(blank=True, null=True, upload_to="cvtae/%Y/%m/%d"),
                ),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "db_table": "empleado",
                "ordering": ["id"],
            },
        ),
    ]
