# Generated by Django 5.1.3 on 2026-02-03 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default=0, max_length=20, verbose_name="Nombres"),
                ),
            ],
            options={
                "verbose_name": "tipo",
                "verbose_name_plural": "tipos",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="emplooye",
            name="type",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="erp.type"
            ),
            preserve_default=False,
        ),
    ]
