# Generated by Django 5.1.3 on 2026-02-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_type_emplooye_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="emplooye",
            name="categ",
            field=models.ManyToManyField(to="erp.category"),
        ),
    ]
