# Generated by Django 5.1.3 on 2026-02-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_category_emplooye_categ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(
                default=0, max_length=20, unique=True, verbose_name="Nombres"
            ),
        ),
    ]
