# Generated by Django 5.1.3 on 2026-02-05 15:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0004_alter_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="Nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Apellidos"),
                ),
                ("dni", models.CharField(max_length=13, unique=True)),
                (
                    "birthday",
                    models.DateField(
                        default=datetime.datetime.now,
                        verbose_name="Fecha de Nacimiento",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        default="male",
                        max_length=10,
                        verbose_name="Sexo",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["id"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(
                default=1, max_length=150, unique=True, verbose_name="Nombre"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product/%Y/%m/%d"
                    ),
                ),
                (
                    "pvp",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "cate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erp.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "iva",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erp.client"
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SaleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erp.product"
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erp.sale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Venta",
                "verbose_name_plural": "Detalles de Ventas",
                "ordering": ["id"],
            },
        ),
        migrations.DeleteModel(name="Emplooye",),
        migrations.DeleteModel(name="Type",),
    ]
